#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.2.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'triggerhappy.service' 'triggerhappy.socket' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.2.1
if [ -x "/etc/init.d/triggerhappy" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native triggerhappy stop || exit 1
fi
# End automatically added section
